use crate::layer1::day_night::TimeOfDay;
use crate::layer1::edicts::{get_morale_modifier, ColonyPolicies};
use crate::layer1::morale::Morale;
use crate::layer1::needs::Needs;
use crate::layer1::social::SocialBuff;
use crate::layer1::traits::{get_trait_mood_modifier, Traits};
use bevy_ecs::prelude::*;

/// Types of memories a pop can acquire.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MemoryType {
    /// Witnessed a pop die.
    WitnessedDeath,
    /// Suffered from starvation (hunger = 0).
    StarvationTrauma,
    /// Ate a high quality meal.
    AteFineMeal,
    /// Won a combat encounter.
    WonFight,
    /// Saw a dead body (corpse).
    SawCorpse,
    /// Attended a funeral (closure).
    AttendedFuneral,
    FleshTaxTrauma,
    /// Slept in an awful room.
    SleptInAwfulRoom,
    /// Slept in a dull room.
    SleptInDullRoom,
    /// Slept in a decent room.
    SleptInDecentRoom,
    /// Slept in a great room.
    SleptInGreatRoom,
    /// Slept in a legendary room.
    SleptInLegendaryRoom,
    /// Ate in an awful room.
    AteInAwfulRoom,
    /// Ate in a dull room.
    AteInDullRoom,
    /// Ate in a decent room.
    AteInDecentRoom,
    /// Ate in a great room.
    AteInGreatRoom,
    /// Ate in a legendary room.
    AteInLegendaryRoom,
    /// Admired a piece of art.
    AdmiredArt,
    /// Disgusted by vermin infestation.
    DisgustedByVermin,
    /// Inspector gave a glowing report.
    InspectorImpressed,
    /// Inspector gave a terrible report.
    InspectorDisappointed,
    /// Fake positive memory generated by a Simulacrum.
    FakePositive,
    /// The colony mascot died.
    MascotDeath,
    /// Lost a limb in an accident.
    LostLimb,
    /// Ate the flesh of another pop (Spec 276: taboo violation).
    CannibalismTaboo,
    /// Psychological trauma from consuming sapient flesh (Spec 276).
    CannibalismTrauma,
}

impl MemoryType {
    /// Returns the mood impact (0.0 to 1.0 or negative).
    #[must_use]
    pub const fn base_mood_impact(&self) -> f32 {
        match self {
            Self::WitnessedDeath => -0.2,
            Self::MascotDeath | Self::LostLimb | Self::FleshTaxTrauma => -0.3, // High impact grief/trauma
            Self::CannibalismTaboo => -0.25,
            Self::CannibalismTrauma => -0.35, // Eating the dead scars deeply
            Self::StarvationTrauma => -0.15,
            Self::DisgustedByVermin | Self::InspectorDisappointed => -0.1,
            Self::InspectorImpressed => 0.15,
            Self::FakePositive => 0.5,
            Self::AteFineMeal | Self::AttendedFuneral => 0.1,
            Self::WonFight | Self::AdmiredArt => 0.05,
            Self::SawCorpse => -0.05,
            Self::SleptInAwfulRoom => -0.1,
            Self::SleptInDullRoom => -0.05,
            Self::SleptInGreatRoom => 0.05,
            Self::SleptInLegendaryRoom => 0.1,
            Self::AteInAwfulRoom => -0.05,
            Self::AteInDullRoom => -0.02,
            Self::SleptInDecentRoom | Self::AteInDecentRoom => 0.0,
            Self::AteInGreatRoom => 0.02,
            Self::AteInLegendaryRoom => 0.05,
        }
    }

    /// Returns the decay rate per tick.
    #[must_use]
    pub const fn decay_rate(&self) -> f32 {
        // Ticks to fade completely
        match self {
            Self::WitnessedDeath | Self::LostLimb | Self::MascotDeath => 0.0005, // Slow fade (2000 ticks)
            Self::CannibalismTaboo | Self::CannibalismTrauma => 0.0005, // Slow fade (2000 ticks): the colony does not forget
            Self::StarvationTrauma | Self::AttendedFuneral | Self::FleshTaxTrauma => 0.001, // Medium
            Self::AteFineMeal | Self::WonFight => 0.002, // Fast (500 ticks)
            Self::SawCorpse | Self::AdmiredArt | Self::DisgustedByVermin => 0.01, // Very fast fade (100 ticks)
            Self::InspectorImpressed | Self::InspectorDisappointed | Self::FakePositive => 0.005, // Medium-long duration (~200 ticks)
            // Room thoughts last 1 day (100 ticks)
            Self::SleptInAwfulRoom
            | Self::SleptInDullRoom
            | Self::SleptInDecentRoom
            | Self::SleptInGreatRoom
            | Self::SleptInLegendaryRoom
            | Self::AteInAwfulRoom
            | Self::AteInDullRoom
            | Self::AteInDecentRoom
            | Self::AteInGreatRoom
            | Self::AteInLegendaryRoom => 0.01,
        }
    }
}

/// A specific instance of a memory on a pop.
#[derive(Debug, Clone)]
pub struct ActiveMemory {
    /// The type of memory.
    pub memory_type: MemoryType,
    /// The tick when it was added.
    pub added_at: u64,
    /// Current intensity (starts at 1.0, decays to 0.0).
    pub intensity: f32,
    /// Indicates if this memory was artificially forged.
    pub forged: bool,
}

/// Component storing all active memories for a pop.
#[derive(Component, Default, Debug, Clone)]
pub struct Memories {
    /// List of active memories.
    pub items: Vec<ActiveMemory>,
}

impl Memories {
    /// Adds a new memory with full intensity.
    pub fn add(&mut self, memory_type: MemoryType, current_tick: u64) {
        self.items.push(ActiveMemory {
            memory_type,
            added_at: current_tick,
            intensity: 1.0,
            forged: false,
        });
    }

    /// Adds a forged memory with full intensity.
    pub fn add_forged(&mut self, memory_type: MemoryType, current_tick: u64) {
        self.items.push(ActiveMemory {
            memory_type,
            added_at: current_tick,
            intensity: 1.0,
            forged: true,
        });
    }

    /// Decays all memories by the given number of ticks.
    /// Removes memories that have faded to 0 intensity.
    pub fn decay(&mut self, ticks_passed: u64) {
        #[allow(clippy::cast_precision_loss)]
        let ticks_f32 = ticks_passed as f32;
        for memory in &mut self.items {
            let decay = memory.memory_type.decay_rate() * ticks_f32;
            memory.intensity = (memory.intensity - decay).max(0.0);
        }
        self.items.retain(|m| m.intensity > 0.0);
    }
}

/// Calculates the raw (unclamped) morale score.
#[must_use]
pub fn calculate_raw_morale(
    needs: &Needs,
    memories: Option<&Memories>,
    social_buff: Option<&SocialBuff>,
    policies: Option<&ColonyPolicies>,
    traits: Option<&Traits>,
    time_of_day: Option<TimeOfDay>,
    morale: Option<&Morale>,
) -> f32 {
    let base = needs.morale();
    let memory_modifier: f32 = memories.map_or(0.0, |m| {
        m.items
            .iter()
            .map(|i| i.memory_type.base_mood_impact() * i.intensity)
            .sum()
    });

    let social_modifier = social_buff.map_or(0.0, |s| s.value);

    let policy_modifier = policies.map_or(0.0, get_morale_modifier);

    let trait_modifier = if let (Some(t), Some(time)) = (traits, time_of_day) {
        get_trait_mood_modifier(t, time)
    } else {
        0.0
    };

    let morale_modifier: f32 =
        morale.map_or(0.0, |m| m.modifiers.iter().map(|modi| modi.value).sum());

    base + memory_modifier + social_modifier + policy_modifier + trait_modifier + morale_modifier
}

/// Calculates the effective morale including memory and social modifiers.
#[must_use]
pub fn calculate_effective_morale(
    needs: &Needs,
    memories: Option<&Memories>,
    social_buff: Option<&SocialBuff>,
    policies: Option<&ColonyPolicies>,
    traits: Option<&Traits>,
    time_of_day: Option<TimeOfDay>,
    morale: Option<&Morale>,
) -> f32 {
    calculate_raw_morale(
        needs,
        memories,
        social_buff,
        policies,
        traits,
        time_of_day,
        morale,
    )
    .clamp(0.0, 1.0)
}

/// System to decay memories every tick.
pub fn memory_decay_system(mut query: Query<&mut Memories>) {
    // Assuming this runs every tick
    query.par_iter_mut().for_each(|mut memories| {
        memories.decay(1);
    });
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::layer1::needs::Needs;

    #[test]
    fn test_add_memory() {
        let mut memories = Memories::default();
        memories.add(MemoryType::WitnessedDeath, 100);

        assert_eq!(memories.items.len(), 1);
        assert_eq!(memories.items[0].memory_type, MemoryType::WitnessedDeath);
        assert_eq!(memories.items[0].added_at, 100);
        assert!((memories.items[0].intensity - 1.0).abs() < f32::EPSILON);
    }

    #[test]
    fn test_memory_decay() {
        let mut memories = Memories::default();
        memories.add(MemoryType::WitnessedDeath, 0);

        // Decay logic: Intensity reduces by decay_rate * ticks
        // WitnessedDeath decay_rate = 0.0005 per tick
        memories.decay(100);

        let expected_intensity = 1.0 - (0.0005 * 100.0);
        assert!((memories.items[0].intensity - expected_intensity).abs() < 0.0001);
        assert!(memories.items[0].intensity < 1.0);
        assert!(memories.items[0].intensity > 0.0);
    }

    #[test]
    fn test_memory_removal_when_faded() {
        let mut memories = Memories::default();
        memories.items.push(ActiveMemory {
            memory_type: MemoryType::WitnessedDeath,
            added_at: 0,
            intensity: 0.0001, // Almost 0
            forged: false,
        });

        // Decay enough to kill it
        // 0.0005 per tick. 1 tick -> -0.0005. 0.0001 - 0.0005 < 0.
        memories.decay(1);

        assert!(memories.items.is_empty());
    }

    #[test]
    fn test_calculate_effective_morale() {
        let needs = Needs {
            hunger: 0.5,
            rest: 0.5,
            leisure: 0.5,
            hygiene: 0.5, // changed to 0.5 so average is 0.5
        };
        let mut memories = Memories::default();

        // Base morale = (0.5+0.5+0.5+0.5)/4 = 0.5
        let _base = needs.morale();

        // WitnessedDeath: -0.2 mood impact at max intensity
        memories.add(MemoryType::WitnessedDeath, 0);

        let effective =
            calculate_effective_morale(&needs, Some(&memories), None, None, None, None, None);

        // 0.5 - 0.2 = 0.3
        assert!((effective - 0.3).abs() < 0.001);
    }

    #[test]
    fn test_multiple_memories_stack() {
        let needs = Needs {
            hunger: 0.5,
            rest: 0.5,
            leisure: 0.5,
            hygiene: 0.5,
        };
        let mut memories = Memories::default();

        memories.add(MemoryType::WitnessedDeath, 0); // -0.2
        memories.add(MemoryType::AteFineMeal, 0); // +0.1

        let effective =
            calculate_effective_morale(&needs, Some(&memories), None, None, None, None, None);

        // 0.5 - 0.2 + 0.1 = 0.4
        assert!((effective - 0.4).abs() < 0.001);
    }

    #[test]
    fn test_morale_clamping() {
        let needs = Needs {
            hunger: 1.0,
            rest: 1.0,
            leisure: 1.0,
            hygiene: 0.8,
        }; // Base 1.0
        let mut memories = Memories::default();
        memories.add(MemoryType::AteFineMeal, 0); // +0.1

        let effective =
            calculate_effective_morale(&needs, Some(&memories), None, None, None, None, None);
        assert!((effective - 1.0).abs() < f32::EPSILON);
    }

    #[test]
    fn test_social_buff_stacking() {
        let needs = Needs {
            hunger: 0.5,
            rest: 0.5,
            leisure: 0.5,
            hygiene: 0.5,
        }; // Base 0.5
        let buff = crate::layer1::social::SocialBuff { value: 0.1 };

        let effective =
            calculate_effective_morale(&needs, None, Some(&buff), None, None, None, None);
        assert!((effective - 0.6).abs() < f32::EPSILON);
    }

    #[test]
    fn test_admired_art_properties() {
        // Base mood impact: 0.05
        assert!((MemoryType::AdmiredArt.base_mood_impact() - 0.05).abs() < f32::EPSILON);

        // Decay rate: 0.01
        assert!((MemoryType::AdmiredArt.decay_rate() - 0.01).abs() < f32::EPSILON);
    }

    #[test]
    fn test_trait_mood_modifier() {
        use crate::layer1::day_night::TimeOfDay;
        use crate::layer1::traits::{Trait, Traits};

        let needs = Needs {
            hunger: 0.5,
            rest: 0.5,
            leisure: 0.5,
            hygiene: 0.5,
        };
        let night_owl = {
            let mut t = Traits::default();
            t.add(Trait::NightOwl);
            t
        };

        // Night time -> +0.1
        let effective = calculate_effective_morale(
            &needs,
            None,
            None,
            None,
            Some(&night_owl),
            Some(TimeOfDay::Night),
            None,
        );
        // 0.5 + 0.1 = 0.6
        assert!((effective - 0.6).abs() < 0.001);

        // Day time -> -0.05
        let effective_day = calculate_effective_morale(
            &needs,
            None,
            None,
            None,
            Some(&night_owl),
            Some(TimeOfDay::Day),
            None,
        );
        // 0.5 - 0.05 = 0.45
        assert!((effective_day - 0.45).abs() < 0.001);
    }
}
