use super::Layer1SystemSet;
use crate::layer1::inspector::spawn_inspector_system;
use crate::layer1::social::old_guard::{
    apply_founder_benefits_system, apply_mood_modifiers_system,
};
use crate::layer1::*;
use bevy_ecs::prelude::*;

#[allow(clippy::too_many_lines)]
pub fn register(schedule: &mut Schedule) {
    schedule.add_systems(
        (
            crate::layer1::economy::information_black_market::check_censorship_threshold_system,
            crate::layer1::economy::information_black_market::process_black_market_drain_system,
            crate::layer1::economy::information_black_market::generate_black_market_intel_system,
            crate::layer1::tech::tick_nostalgia_engine,
            crate::layer1::tech::process_pilgrim_fees,
        )
            .in_set(Layer1SystemSet::Economy),
    );
    schedule.add_systems(
        crate::layer1::fauna::modular_fauna::evaluate_modular_fauna_stats_system
            .in_set(Layer1SystemSet::Economy),
    );

    schedule.add_systems(
        (
            crate::layer1::architecture::sunk_cost_monument::calculate_sunk_cost_upkeep_system,
            crate::layer1::core::integration::sunk_cost_resource_drain_system.after(
                crate::layer1::architecture::sunk_cost_monument::calculate_sunk_cost_upkeep_system,
            ),
            crate::layer1::architecture::sunk_cost_monument::handle_monument_cancellation_system
                .after(crate::layer1::core::integration::sunk_cost_resource_drain_system),
            crate::layer1::architecture::sunk_cost_monument::apply_ruin_morale_penalty_system,
            crate::layer1::anomalies::benevolent_malfunctions::apply_malfunction_effects,
            crate::layer1::anomalies::benevolent_malfunctions::apply_malfunction_quirks,
            crate::layer1::anomalies::benevolent_malfunctions::process_repairs,
            update_resource_caps_system,
            crate::layer1::digital_immortality::ghost_power_consumption,
            advance_season_system,
            crate::layer1::core::integration::predecessor_weather_array_bridge_system
                .after(advance_season_system),
        )
            .in_set(Layer1SystemSet::Economy),
    );
    schedule.add_systems(
        (
            crate::layer1::administration::feral_administration::spawn_unprocessed_forms_system,
            crate::layer1::administration::feral_administration::process_impassable_terrain_system,
            crate::layer1::administration::feral_administration::feral_admin_chronicle_bridge,
            update_taboo_duration_system,
            update_water_system,
            update_weather_system,
            crate::layer1::agriculture::pollination::drone_pollination_system,
            crate::layer1::agriculture::pollination::process_crop_growth_system
                .after(crate::layer1::agriculture::pollination::drone_pollination_system),
            crate::layer1::fertility::update_fertility_system,
            produce_food_system.after(crate::layer1::fertility::update_fertility_system),
            crate::layer1::husbandry::husbandry_production_system.after(produce_food_system),
            (
                hopper_system.after(produce_food_system),
                process_refining_system,
                crate::layer1::tech::rhythm::update_rhythm_system.after(process_refining_system),
                crate::layer1::social::cadet::process_allowance_system,
                crate::layer2::designation::evaluate_designation_bonuses,
                crate::layer2::designation::handle_designation_changes,
                (
                    crate::layer1::gene_bank::process_cloning_system,
                    crate::layer1::genetics::process_gene_splicing_system,
                    crate::layer1::genetics::apply_crop_traits,
                    crate::layer1::genetics::process_mutations,
                    crate::layer1::biology::genetics::splicers_dilemma::apply_mutation_system,
                ),
                crate::layer1::clone_vat::process_clone_vats_system,
                crate::layer1::permit::permit_activation_system,
                crate::layer1::permit::enforce_permit_restrictions_system
                    .before(crate::layer1::energy::power_grid_system),
                crate::layer1::tech::update_tech_capacity_system,
                crate::layer1::skills::generational_atrophy::apply_skill_atrophy_system,
                crate::layer1::tech::infinite_archive::update_efficiency_system
                    .after(crate::layer1::tech::update_tech_capacity_system),
                crate::layer1::admin::calculate_admin_stats,
                crate::layer1::tech::martyrs_engine::process_martyrs_engine,
                crate::layer1::eureka::handle_eureka_events,
                recycle_processing_system,
                crate::layer1::exodus::cannibalize_infrastructure_system,
                crate::layer1::exodus::build_ark_system
                    .after(crate::layer1::exodus::cannibalize_infrastructure_system),
                #[cfg(feature = "nova")]
                crate::layer1::machine_consciousness::consciousness_growth_system,
            ),
        )
            .in_set(Layer1SystemSet::Economy),
    );

    schedule.add_systems(
        (
            crate::layer1::energy::sky_tether::auroral_harvesting_system,
            crate::layer1::administration::invasive_bureaucracy::expand_bureaucracy_nodes_system,
            crate::layer1::administration::invasive_bureaucracy::calculate_bureaucracy_stability_system.after(crate::layer1::administration::invasive_bureaucracy::expand_bureaucracy_nodes_system),
        )
            .in_set(Layer1SystemSet::Economy),
    );

    schedule.add_systems(
        (
            process_research_system,
            process_observe_system,
            #[cfg(feature = "nova")]
            crate::layer1::constellations::observe_constellations_system,
            #[cfg(feature = "nova")]
            crate::layer1::void_signals::scan_for_signals_system,
            #[cfg(feature = "nova")]
            crate::layer1::void_signals::auto_tune_system,
            #[cfg(feature = "nova")]
            crate::layer1::void_signals::decrypt_signals_system,
            regrowth_system,
            crate::layer1::ecology::process_ecological_succession,
            flora_spread_system,
            mastery_accumulation_system,
            crate::layer1::cybernetics::surgery_system,
            crate::layer1::institutional_memory::produce_manual_system,
            crate::layer1::institutional_memory::manual_aura_system,
            crate::layer1::tech::ghost_code::residue_system,
            crate::layer1::tech::ghost_code::ghost_infection_system,
            crate::layer1::tech::ghost_code::apply_ghost_traits_system,
            crate::layer1::tech::living_archive::process_flesh_server_stress_system,
            crate::layer1::tech::living_archive::flesh_server_nutrient_consumption_system,
            (
                crate::layer1::hologram::update_holograms_system,
                crate::layer1::hologram::apply_disillusionment_system,
            )
                .chain(),
        )
            .in_set(Layer1SystemSet::Economy),
    );

    schedule.add_systems(
        (
            restore_rest_in_housing_system,
            crate::layer1::psychology::void_sleep::gravity_nightmares_system.after(restore_rest_in_housing_system),
            restore_leisure_system,
            crate::layer1::economy::apex_diet::apply_apex_mutations,
            crate::layer1::economy::apex_diet::process_apex_meat_consumption,
            crate::layer1::social::hedonic_treadmill_integration::hedonic_treadmill_consumption_bridge,
            crate::layer1::social::hedonic_treadmill::process_consumption_quality
                .after(crate::layer1::social::hedonic_treadmill_integration::hedonic_treadmill_consumption_bridge),
            crate::layer1::tech_envy::tech_envy_system.after(restore_leisure_system),
            #[cfg(feature = "nova")]
            crate::layer1::loci::apply_loci_effects_system.after(restore_leisure_system),
            apply_mood_modifiers_system.after(restore_leisure_system),
            mascot_buff_system.after(restore_leisure_system),
            crate::layer1::graffiti::graffiti_observation_system.after(apply_mood_modifiers_system),
            crate::layer1::memetics::memetic_hazards::process_memetic_transmission_system.after(crate::layer1::graffiti::graffiti_observation_system),
            crate::layer1::memetics::parasitic_broadcast_risk_system,
            crate::layer1::memetics::process_parasitic_work_reduction,
            apply_catharsis_morale_bonus_system.after(apply_mood_modifiers_system),
            crate::layer1::law::penal::apply_harvesting_horror_system
                .after(apply_mood_modifiers_system),
            update_morale_cache_system
                .after(apply_catharsis_morale_bonus_system)
                .after(crate::layer1::graffiti::graffiti_observation_system)
                .after(mascot_buff_system),
            morale_decay_system.after(update_morale_cache_system),
            crate::layer1::social::hedonic_treadmill::decay_standard_of_living,
        )
            .in_set(Layer1SystemSet::Economy),
    );
    schedule.add_systems(
        (crate::layer1::private_stash::stash_creation_system,).in_set(Layer1SystemSet::Economy),
    );

    schedule.add_systems(
        crate::layer1::economy::black_market::black_market_economy_system
            .in_set(Layer1SystemSet::Economy),
    );
    schedule.add_systems(
        (
            crate::layer1::economy::black_market::black_market_spawn_system,
            crate::layer1::economy::black_market::smuggler_trade_system,
            crate::layer1::economy::black_market::handle_smuggler_arrival,
            crate::layer1::economy::black_market::pop_smuggling_system,
            crate::layer1::economy::black_market::shutdown_drop_node_system,
        )
            .in_set(Layer1SystemSet::Economy),
    );

    schedule.add_systems(
        (crate::layer1::law::penal::process_dead_pops_for_organs_system,)
            .in_set(Layer1SystemSet::Economy),
    );
    schedule.add_systems(
        (
            crate::layer1::economy::debt_of_the_dead::process_debt_of_the_dead_system,
            crate::layer1::economy::debt_of_the_dead::apply_socialized_debt_system,
        )
            .in_set(Layer1SystemSet::Economy),
    );
    schedule.add_systems(
        (
            crate::layer1::economy::remittances::process_remittances_system,
            healing_system,
            crate::layer1::integration::medical_debt_bridge_system.after(healing_system),
            crate::layer1::beauty::update_beauty_grid_system,
            crate::layer1::window::update_window_views_system
                .after(crate::layer1::beauty::update_beauty_grid_system),
            crate::layer1::beauty::apply_beauty_effects_system
                .after(crate::layer1::window::update_window_views_system),
            check_heirloom_status_system,
            crate::layer1::trade::merchant_arrival_system,
            crate::layer1::law::contraband::enforce_prohibition_system,
            crate::layer1::visitor::spawn_visitor_system,
            spawn_inspector_system.after(crate::layer1::visitor::spawn_visitor_system),
            process_fuel_consumption_system,
            crate::layer1::energy::update_auroral_output_system,
            crate::layer1::solar::update_solar_cycle_system,
            crate::layer1::solar::update_solar_output_system
                .after(crate::layer1::solar::update_solar_cycle_system),
            crate::layer1::energy::power_grid_system
                .after(process_fuel_consumption_system)
                .after(crate::layer1::energy::update_auroral_output_system)
                .after(crate::layer1::solar::update_solar_output_system),
            crate::layer1::energy::load_limits::evaluate_grid_load_system
                .after(crate::layer1::energy::power_grid_system),
            ai_automation_system.after(crate::layer1::energy::power_grid_system),
            ai_rogue_system,
            crate::layer3::market::quantum_famine::process_market_panic_hoarding,
        )
            .in_set(Layer1SystemSet::Economy),
    );
    schedule.add_systems(
        crate::layer3::integration::quantum_famine_export_dump_bridge
            .after(crate::layer3::market::quantum_famine::process_market_panic_hoarding)
            .in_set(Layer1SystemSet::Economy),
    );
    // Spec 1374: resonance crystals harvest tile noise into PowerSource output.
    // Separate add_systems: the main Economy tuple is at Bevy's 20-system
    // limit, and .after() on power_grid_system alone would not schedule this.
    schedule.add_systems(
        crate::layer1::physics::resonance::process_resonance_power_system
            .before(crate::layer1::energy::power_grid_system)
            .in_set(Layer1SystemSet::Economy),
    );
    schedule.add_systems(
        (
            crate::layer1::economy::existential_audit::existential_audit_system,
            crate::layer1::economy::existential_audit::existential_crisis_decay_system,
            crate::layer1::core::integration::existential_audit_chronicle_bridge,
        )
            .chain()
            .in_set(Layer1SystemSet::Economy),
    );

    schedule.add_systems(
        crate::layer1::economy::deep_sleep_syndicates::process_thaw_syndicate_event
            .in_set(Layer1SystemSet::Economy),
    );

    schedule.add_systems(
        (
            crate::layer1::economy::inflation::trigger_market_crash,
            crate::layer1::economy::inflation::process_barter_trade,
        )
            .in_set(Layer1SystemSet::Economy),
    );

    schedule.add_systems(
        (
            crate::layer1::memorial_economy::ancestral_server::handle_engram_upload_system,
            crate::layer1::memorial_economy::ancestral_server::scale_server_power_demand_system,
        )
            .in_set(Layer1SystemSet::Economy),
    );

    schedule.add_systems(
        (
            crate::layer1::economy::beacon::process_colony_beacon_system,
            crate::layer1::economy::beacon::toggle_beacon_system,
            crate::layer1::integration::beacon_migrant_arrival_bridge,
            crate::layer1::integration::beacon_trade_ship_bridge,
            crate::layer1::integration::beacon_pirate_raid_bridge,
            crate::layer1::economy::smugglers_cove::spawn_smugglers_cove_system,
            crate::layer1::economy::smugglers_cove::process_smuggler_decay_system,
        )
            .in_set(Layer1SystemSet::Economy),
    );

    schedule.add_systems(
        (crate::layer1::core::integration::tether_stump_lost_tech_bridge,)
            .in_set(Layer1SystemSet::Economy),
    );

    schedule.add_systems(
        (
            crate::layer1::integration::grid_overload_fire_bridge
                .after(crate::layer1::energy::power_grid_system),
            art_generation_system,
            crate::layer1::petrification::petrification_exposure_system,
            crate::layer1::petrification::petrification_progression_system,
            crate::layer1::petrification::petrification_transformation_system,
            crate::layer1::factions::update_faction_membership_system,
            crate::layer1::administration::bureaucratic_redlining::bureaucratic_redlining_system,
            crate::layer1::administration::bureaucratic_redlining::stateless_expansion_system,
            crate::layer1::administration::bureaucratic_redlining::stateless_squatter_raid_system,
            crate::layer1::administration::bureaucratic_redlining::apply_squatter_visuals_system,
            crate::layer1::factions::update_faction_satisfaction_system
                .after(crate::layer1::factions::update_faction_membership_system),
            crate::layer1::factions::update_faction_demands_system
                .after(crate::layer1::factions::update_faction_satisfaction_system),
            crate::layer1::factions::update_faction_strikes_system
                .after(crate::layer1::factions::update_faction_demands_system),
            crate::layer1::core::integration::faction_strike_mob_bridge_system
                .after(crate::layer1::factions::update_faction_strikes_system),
            crate::layer1::social::sub_lithic::process_deep_mining_exposure,
            crate::layer1::social::sub_lithic::evaluate_cult_formation,
            crate::layer1::social::sub_lithic::process_cult_sabotage,
            apply_founder_benefits_system,
            // Layer 2 visibility systems are handled in simulation.rs
        )
            .in_set(Layer1SystemSet::Economy),
    );
    schedule.add_systems(
        (
            crate::layer1::energy::phantom_grid::phantom_grid_disconnection_system
                .before(crate::layer1::energy::phantom_grid::phantom_grid_connection_system),
            crate::layer1::energy::phantom_grid::phantom_grid_connection_system
                .after(crate::layer1::energy::power_grid_system),
        )
            .in_set(Layer1SystemSet::Economy),
    );
    schedule.add_systems(
        (
            crate::layer1::environment::ephemeral_moons::apply_moon_modifiers_system
                .after(crate::layer1::solar::update_solar_output_system)
                .before(crate::layer1::energy::power_grid_system),
        )
            .in_set(Layer1SystemSet::Economy),
    );

    schedule.add_systems(
        (
            crate::layer1::economy::photophobic::update_photophobic_light_level_system,
            crate::layer1::economy::photophobic::photophobic_degradation_system,
            crate::layer1::economy::photophobic::mining_in_dark_stress_system,
            crate::layer1::artists_muse::evaluate_art_quality_system,
            (
                crate::layer1::cassandra_protocol::activate_cassandra_protocol,
                crate::layer1::core::integration::cassandra_protocol_chronicle_bridge
                    .after(crate::layer1::cassandra_protocol::activate_cassandra_protocol),
            ),
            crate::layer1::cassandra_protocol::handle_disaster_strike,
            crate::layer1::ransom_broker::ransom_demand_system,
            crate::layer1::ransom_broker::process_ransom_decisions_system,
            crate::layer1::core::integration::update_renown_from_morale_system,
            crate::layer1::living_score::update_living_score_aesthetics,
            crate::layer1::infrastructure::subconscious_grid::calculate_colony_stress_system,
            crate::layer1::infrastructure::subconscious_grid::apply_subconscious_grid_effects_system
,
            crate::layer1::infrastructure::subconscious_grid::update_machine_efficiency_system
,
            crate::layer1::infrastructure::subconscious_grid::apply_subconscious_grid_machine_effects_system
,
            crate::layer1::infrastructure::subconscious_grid::apply_lockdown_system,
            crate::layer1::core::integration::sync_scarcity_resources_bridge_system,
            crate::layer1::bureaucracy_of_scarcity::evaluate_scarcity_system,
            crate::layer1::bureaucracy_of_scarcity::apply_rationing_buff_system,
            crate::layer1::core::integration::apply_scarcity_rationing_bridge_system,
            crate::layer1::core::integration::sync_scarcity_jobs_bridge_system
,
        )
            .chain()
            .in_set(Layer1SystemSet::Economy),
    );

    #[cfg(feature = "nova")]
    crate::experimental::radioactive_batteries::register(schedule);
    #[cfg(feature = "nova")]
    crate::experimental::stowaway_clutter::register(schedule);

    #[cfg(feature = "nova")]
    crate::experimental::gluttonous_aroma::register(schedule);

    #[cfg(feature = "nova")]
    crate::experimental::hedonic_halo::register(schedule);

    schedule.add_systems(
        (
            crate::layer1::shipbreaking_symbiotic::simulate_shipbreaker_salvage,
            crate::layer1::core::integration::symbiotic_salvage_chronicle_bridge,
            crate::layer1::core::integration::edible_architecture_chronicle_bridge,
            crate::layer1::energy::gravity_siphon::process_singularity_energy_system,
            crate::layer1::energy::gravity_siphon::process_singularity_mass_accumulation_system,
            crate::layer1::energy::gravity_siphon::trigger_orbital_decay_system,
            crate::layer1::core::integration::gravity_siphon_chronicle_bridge,
            crate::layer1::fungal_network::process_spore_taps_system,
            crate::layer1::crafting::byproducts::complete_crafting_system,
            crate::layer1::crafting::byproducts::waste_dumping_system,
        )
            .chain()
            .in_set(Layer1SystemSet::Economy),
    );
}
