use super::Layer1SystemSet;
use crate::layer1::entities::blob::{
    blob_consumption_system, blob_expansion_system, blob_spread_system,
};
use crate::layer1::*;
use bevy_ecs::prelude::*;

#[allow(clippy::too_many_lines)]
pub fn register(schedule: &mut Schedule) {
    schedule.add_systems(
        (
            crate::layer1::predecessors::predecessor_ruins_passive_bonus_system,
            crate::layer1::nature::crustal_tides::process_crustal_tides,
            crate::layer1::predecessors::predecessor_ruins_trigger_system,
            crate::layer1::predecessors::predecessor_ruins_awakening_system,
            crate::layer1::core::integration::apply_ruin_environmental_buffs_system,
            crate::layer1::core::integration::trigger_ruin_machinery_system,
            crate::layer1::core::integration::apply_ruin_psychological_stress_system,
            crate::layer1::core::integration::architecture_of_regret_bridge_system,
        )
            .chain()
            .in_set(Layer1SystemSet::Environment),
    );
    schedule.add_systems(
        (
            crate::layer1::environment::geothermal::geothermal_pulse_system,
            crate::layer1::environment::geothermal::geothermal_boost_system,
            crate::layer1::environment::geothermal::geothermal_decay_system,
        )
            .in_set(Layer1SystemSet::Environment),
    );
    schedule.add_systems(
        (
            crate::layer1::anomalies::echo::create_echo_source_system,
            crate::layer1::anomalies::echo::manifest_echo_system,
            crate::layer1::anomalies::echo::despawn_echo_system,
            crate::layer1::anomalies::echo::echo_reaction_system,
        )
            .chain()
            .in_set(Layer1SystemSet::Environment),
    );
    schedule.add_systems(
        (
            crate::layer1::shadow_market::despawn_in_light_system,
            crate::layer1::shadow_market::spawn_shadow_trader_system,
        )
            .in_set(Layer1SystemSet::Environment),
    );
    schedule.add_systems(
        (
            crate::layer1::environment::orbital_tether::detect_tether_destruction_system,
            crate::layer1::environment::orbital_tether::process_tether_whip_system.after(
                crate::layer1::environment::orbital_tether::detect_tether_destruction_system,
            ),
        )
            .in_set(Layer1SystemSet::Environment),
    );
    schedule.add_systems(
        (
            fire_pressure_check_system,
            fire_spread_system.after(fire_pressure_check_system),
            fire_damage_pops_system.after(fire_spread_system),
            crate::layer1::structure::fire_damage_structure_system.after(fire_spread_system),
            fire_damage_system
                .after(fire_spread_system)
                .after(fire_damage_pops_system)
                .after(crate::layer1::structure::fire_damage_structure_system),
            (
                blob_expansion_system,
                crate::layer1::entities::blob::blob_building_destruction_system
                    .after(blob_expansion_system),
                blob_spread_system,
                blob_consumption_system,
            ),
            blob_consumption_system.after(blob_spread_system),
            flora_attack_system,
            crate::layer1::flora::process_flora_migration,
            ancient_structure_decay_system,
            crate::layer1::graffiti::graffiti_decay_system,
            crate::layer1::environment::orbital_crossfire::impact_system,
            crate::layer1::environment::volatile::volatile_decay_system,
            crate::layer1::environment::volatile::handle_explosion_system
                .after(crate::layer1::environment::volatile::volatile_decay_system),
        )
            .in_set(Layer1SystemSet::Environment),
    );
    schedule.add_systems(
        (
            crate::layer1::environment::impact::process_impact_countdown_system,
            crate::layer1::environment::impact::process_impact_strike_system,
            crate::layer1::logistics::pneumatic::tube_clog_system,
            crate::layer1::ecology::biome_collapse_system,
            crate::layer1::social::grievances::decay_notes_system,
            crate::layer1::hum::update_hum_system,
            crate::layer1::environment::bio_acoustic_miasma::update_miasma_clouds,
            crate::layer1::architecture::embezzlement::process_embezzlement,
            crate::layer1::core::integration::embezzlement_chronicle_bridge,
            crate::layer1::parasitic_architecture::process_megastructure_consumption,
        )
            .in_set(Layer1SystemSet::Environment),
    );
    schedule.add_systems(
        (
            crate::layer1::nature::megafauna_terrain::process_mining_titan_system,
            crate::layer1::nature::megafauna_terrain::awaken_titan_system
                .after(crate::layer1::nature::megafauna_terrain::process_mining_titan_system),
        )
            .in_set(Layer1SystemSet::Environment),
    );
    schedule.add_systems(
        (
            crate::layer1::architecture::biomimetic::adjust_sympathetic_infrastructure_system,
            crate::layer1::architecture::living_architecture::living_building_healing_system,
            crate::layer1::architecture::living_architecture::living_building_consume_pop_system,
            crate::layer1::architecture::smart_matter::update_smart_matter_state,
        )
            .in_set(Layer1SystemSet::Environment),
    );
    schedule.add_systems(
        (crate::layer1::energy::phantom_grid::phantom_grid_hum_system,)
            .in_set(Layer1SystemSet::Environment),
    );
    schedule.add_systems(
        (
            crate::layer1::temporal_ghost_towns::process_temporal_stutters,
            crate::layer1::temporal_ghost_towns::process_temporal_recovery,
            crate::layer1::environment::ephemeral_moons::handle_moon_capture_system,
            crate::layer1::environment::ephemeral_moons::decay_ephemeral_moons_system,
        )
            .in_set(Layer1SystemSet::Environment),
    );
    schedule.add_systems(
        (
            crate::layer1::environment::photophobic::photophobic_decay_system,
            crate::layer1::geodetic::update_living_stone_system,
            crate::layer1::geodetic::form_golem_system
                .after(crate::layer1::geodetic::update_living_stone_system),
            crate::layer1::integration::golem_formed_chronicle_bridge_system
                .after(crate::layer1::geodetic::form_golem_system),
        )
            .in_set(Layer1SystemSet::Environment),
    );
    schedule.add_systems(
        (
            crate::layer1::environment::geomes::diffuse_geome_hazards_system,
            crate::layer1::environment::geomes::environmental_damage_system
                .after(crate::layer1::environment::geomes::diffuse_geome_hazards_system),
        )
            .in_set(Layer1SystemSet::Environment),
    );

    schedule.add_systems(
        (
            crate::layer1::clutter::clutter_accumulation_system,
            crate::layer1::environment::artificial_sunspots::apply_sunspot_effects_system,
            crate::layer1::environment::artificial_sunspots::update_outdoor_exposure_system,
            crate::layer1::environment::artificial_sunspots::apply_sunspot_radiation_system.after(
                crate::layer1::environment::artificial_sunspots::update_outdoor_exposure_system,
            ),
            crate::layer1::environment::artificial_sunspots::track_sunspot_chronicle_system,
            (
                crate::layer1::environment::terminator_habitats::apply_libration_wobble_system,
                crate::layer1::environment::terminator_habitats::calculate_tile_temperatures_system,
                crate::layer1::environment::terminator_habitats::building_temperature_damage_system,
            )
                .chain(),
        )
            .in_set(Layer1SystemSet::Environment),
    );

    schedule.add_systems(
        (
            crate::layer1::environment::seismic::update_seismic_system,
            crate::layer1::environment::seismic::seismic_flora_reaction_system
                .after(crate::layer1::environment::seismic::update_seismic_system),
            crate::layer1::environment::seismic::seismic_instability_system
                .after(crate::layer1::environment::seismic::update_seismic_system),
            crate::layer1::geology::seismic_decay_system,
            crate::layer1::geology::subsurface::kinetic_strike_system,
            crate::layer1::geology::check_seismic_events
                .after(crate::layer1::geology::seismic_decay_system),
            crate::layer1::geology::apply_geological_event_system
                .after(crate::layer1::geology::check_seismic_events)
                .after(crate::layer1::environment::seismic::seismic_instability_system),
            crate::layer1::core::integration::trigger_tectonic_fracking_system,
            crate::layer1::core::integration::heavy_industry_tectonic_stress_bridge,
            crate::layer1::geology::tectonic::update_stress_system,
        )
            .in_set(Layer1SystemSet::Environment),
    );
    schedule.add_systems(
        (
            crate::layer1::geology::fracking::tectonic_fracking_system
                .after(crate::layer1::core::integration::trigger_tectonic_fracking_system),
            crate::layer1::geology::tectonic::trigger_relief_quake_system
                .after(crate::layer1::geology::tectonic::update_stress_system),
            crate::layer1::geology::tectonic::check_quake_system
                .after(crate::layer1::geology::tectonic::trigger_relief_quake_system),
            crate::layer1::geology::tectonic::apply_mega_quake_damage_system
                .after(crate::layer1::geology::tectonic::check_quake_system),
            spirit_decay_system,
            quirk_generation_system.after(spirit_decay_system),
            entropy_system,
            crate::layer1::structure::fragile_decay_system.after(entropy_system),
            crate::layer1::crowding::crowding_decay_system,
            #[cfg(feature = "nova")]
            crate::layer1::loci::update_loci_system,
        )
            .in_set(Layer1SystemSet::Environment),
    );

    schedule.add_systems(
        (crate::layer1::social::empty_room::update_sanctuary_system,)
            .in_set(Layer1SystemSet::Environment),
    );

    schedule.add_systems(
        (
            crate::layer1::atmosphere::update_atmospheric_tide_system,
            crate::layer1::atmosphere::sync_global_wind_system
                .after(crate::layer1::atmosphere::update_atmospheric_tide_system),
            crate::layer1::wind::update_wind_system
                .after(crate::layer1::atmosphere::sync_global_wind_system),
            // Spec 1374: canyon map refreshes sparingly from terrain heights.
            crate::layer1::physics::resonance::recompute_canyon_map_system
                .after(crate::layer1::wind::update_wind_system),
            #[cfg(feature = "nova")]
            crate::layer1::constellations::update_sky_system,
            malfunction_system.after(entropy_system),
            crate::layer1::resources::waste_pollution_bridge,
            crate::layer1::nature::biosphere_empathy::sync_empathic_network_system,
            crate::layer1::nature::biosphere_empathy::handle_flora_damage_empathy_system,
            crate::layer1::atmosphere::update_atmosphere_system
                .after(crate::layer1::resources::waste_pollution_bridge)
                .after(crate::layer1::wind::update_wind_system),
            crate::layer1::atmosphere::corrosion_damage_system
                .after(crate::layer1::atmosphere::update_atmosphere_system),
            crate::layer1::environment::terraforming::update_planetary_atmosphere_system
                .after(crate::layer1::atmosphere::update_atmosphere_system),
            crate::layer1::atmosphere::update_weather_diffusion_system.after(
                crate::layer1::environment::terraforming::update_planetary_atmosphere_system,
            ),
            crate::layer1::environment::terraforming::apply_planetary_effects_system
                .after(crate::layer1::atmosphere::update_weather_diffusion_system),
            crate::layer1::atmosphere::simulate_diffusion_system
                .after(crate::layer1::environment::terraforming::apply_planetary_effects_system),
            crate::layer1::environment::mycorrhizal_network::fungal_network_sharing_system,
            crate::layer1::environment::fungal_monoliths::fungal_monolith_eruption_system,
            crate::layer1::environment::mycorrhizal_network::fungal_tax_system,
            crate::layer1::logistics::orbital_drop::process_orbital_drops,
            crate::layer1::nanite_storms::apply_nanite_storm_effects,
            crate::layer1::environment::orbital_junkyard::process_debris_rain,
        )
            .in_set(Layer1SystemSet::Environment),
    );
    schedule.add_systems(
        (crate::layer1::environment::orbital_junkyard::process_falling_debris,)
            .in_set(Layer1SystemSet::Environment),
    );

    schedule.add_systems(
        (
            update_pressure_system,
            crate::layer1::physics::pressure::lifesupport_damage_warning_system
                .after(update_pressure_system),
            crate::layer1::physics::pressure::lifesupport_self_repair_system
                .after(update_pressure_system),
            update_noise_system.after(update_pressure_system),
            // Spec 1374: canyon howling adds noise after the reset/propagation,
            // before the leisure/morale drain sees it.
            crate::layer1::physics::resonance::calculate_howling_system
                .after(update_noise_system),
            crate::layer1::physics::resonance::howling_chronicle_system
                .after(crate::layer1::physics::resonance::calculate_howling_system),
            apply_noise_effects_system
                .after(crate::layer1::physics::resonance::calculate_howling_system),
            crate::layer1::temperature::update_temperature_system.after(update_pressure_system),
            crate::layer1::radioactive::radiation_system
                .after(crate::layer1::temperature::update_temperature_system),
            crate::layer1::suction::suction_system.after(update_pressure_system),
            crate::layer1::integration::vacuum_clears_pollution_system
                .after(crate::layer1::atmosphere::update_atmosphere_system)
                .after(update_pressure_system),
            biocompatibility_system.after(crate::layer1::atmosphere::update_atmosphere_system),
            crate::layer1::pheromone::reactive_emitter_system
                .after(crate::layer1::atmosphere::update_atmosphere_system),
            crate::layer1::pheromone::pheromone_emission_system
                .after(crate::layer1::pheromone::reactive_emitter_system),
            crate::layer1::biology::gravity_caste::adapt_gravity_caste_system,
            crate::layer1::biology::gravity_caste::apply_gravity_penalties_system
                .after(crate::layer1::biology::gravity_caste::adapt_gravity_caste_system),
        )
            .in_set(Layer1SystemSet::Environment),
    );
}
