use super::Layer1SystemSet;
use crate::layer1::direct_link::{apply_buffs, handle_direct_movement, handle_possession};
use crate::layer1::*;
use bevy_ecs::prelude::*;

#[allow(clippy::too_many_lines)]
pub fn register(schedule: &mut Schedule) {
    schedule.add_systems(
        (
            crate::layer1::heroic_acts::activate_heroic_act_system,
            crate::layer1::heroic_acts::resolve_heroic_acts_system,
        )
            .in_set(Layer1SystemSet::Execution),
    );

    #[cfg(feature = "nova")]
    crate::experimental::hoarder_comfort::register(schedule);
    schedule
        .add_systems(crate::layer1::tech::process_ego_machine.in_set(Layer1SystemSet::Execution));
    schedule.add_systems(
        crate::layer1::tech::process_ego_social_friction.in_set(Layer1SystemSet::Execution),
    );
    schedule.add_systems(
        crate::layer1::hazards::harvester_meteor_absorption_system
            .in_set(Layer1SystemSet::Execution),
    );
    schedule.add_systems(
        (
            crate::layer1::shadow_ecosystems::spawn_data_fauna,
            crate::layer1::shadow_ecosystems::data_fauna_feeding,
            crate::layer1::shadow_ecosystems::data_fauna_overfeed,
            crate::layer1::shadow_ecosystems::reveal_data_fauna,
        )
            .chain()
            .in_set(super::Layer1SystemSet::Execution),
    );

    schedule.add_systems(
        (
            crate::layer1::administration::sentient_bureaucracy::update_bureaucracy_sentience_system,
            crate::layer1::administration::sentient_bureaucracy::autonomous_work_reassignment_system,
        ).chain().in_set(super::Layer1SystemSet::Execution),
    );
    schedule.add_systems(
        crate::layer1::architecture::gravity_engineering::evaluate_structural_integrity_system
            .in_set(super::Layer1SystemSet::Execution),
    );
    schedule.add_systems(
        crate::layer1::actions::escape::process_lifeboat_launches
            .in_set(super::Layer1SystemSet::Execution),
    );
    schedule.add_systems(
        (
            crate::layer1::mobile_architecture::transform_building_system,
            crate::layer1::mobile_architecture::move_mobile_building_system,
        )
            .chain()
            .in_set(super::Layer1SystemSet::Execution),
    );
    schedule.add_systems(
        (
            crate::layer1::tech::rogue_automation_cults::rogue_cult_formation_system,
            crate::layer1::tech::rogue_automation_cults::cult_priority_override_system,
            crate::layer1::core::integration::rogue_cult_chronicle_bridge,
        )
            .chain()
            .in_set(super::Layer1SystemSet::Execution),
    );

    schedule.add_systems(
        crate::layer1::social::zero_g_sports::zero_g_sports_system
            .in_set(super::Layer1SystemSet::Execution),
    );
    schedule.add_systems(
        (
            crate::layer1::social::protest_crowds::form_mob_system,
            crate::layer1::mind::sleep_debt::process_sleep_debt_system,
            crate::layer1::mind::sleep_debt::check_critical_sleep_debt_system,
            crate::layer1::core::integration::repo_man_arrival_bridge,
            crate::layer1::mind::sleep_debt::process_repo_men_action_system,
            crate::layer1::social::protest_crowds::disperse_mob_system,
        )
            .in_set(super::Layer1SystemSet::Execution),
    );
    schedule.add_systems(
        (
            crate::layer1::zone::apply_zone_designation_system,
            crate::layer1::digital_immortality::handle_mind_upload,
            crate::layer1::digital_immortality::process_ghost_hacks,
            crate::layer1::construction::process_great_work_phases,
            crate::layer1::room_quality::apply_waking_thoughts_system
                .after(crate::layer1::zone::apply_zone_designation_system),
            assign_sleepwalk_target_system
                .after(crate::layer1::room_quality::apply_waking_thoughts_system),
            cleanup_previous_assignment_system.after(assign_sleepwalk_target_system),
            crate::layer1::customs::immigration_interception_system
                .after(cleanup_previous_assignment_system),
            crate::layer1::tech::rhythm::update_rhythm_system
                .after(cleanup_previous_assignment_system),
            handle_possession.before(process_start_plan_system),
            apply_buffs.after(handle_possession),
            crate::layer1::artifacts::vr_pod::update_vr_pods_system
                .after(cleanup_previous_assignment_system),
            crate::layer1::artifacts::vr_pod::cleanup_vr_pod_status_system
                .after(crate::layer1::artifacts::vr_pod::update_vr_pods_system),
            process_start_plan_system
                .after(crate::layer1::customs::immigration_interception_system),
            crate::layer1::drone::drone_spawner_bridge_system.after(process_start_plan_system),
            crate::layer1::drone::drone_work_bridge_system.after(process_start_plan_system),
            crate::layer1::husbandry::pasture_confinement_system.after(process_start_plan_system),
            crate::layer1::fauna::fauna_behavior_system.after(process_start_plan_system),
            mascot_behavior_system.after(process_start_plan_system),
            crate::layer1::the_visitor::the_visitor_behavior_system
                .after(process_start_plan_system),
        )
            .in_set(Layer1SystemSet::Execution),
    );

    // UI state sync for adventurer possession: updates
    // `UiState::suppress_global_ui` and the input context stack from the same
    // possess/unpossess events. Read-only w.r.t. the sim.
    schedule.add_systems(
        crate::ui::input::handle_possession_ui_state
            .after(handle_possession)
            .in_set(Layer1SystemSet::Execution),
    );

    schedule.add_systems(
        (crate::layer1::core::integration::trigger_shift_end_system
            .after(crate::layer1::day_night::update_day_night_cycle_system),)
            .in_set(Layer1SystemSet::Execution),
    );

    schedule.add_systems(
        (
            crate::layer1::day_night::update_day_night_cycle_system
                .after(process_start_plan_system),
            crate::layer1::day_night::update_ambient_light_from_cycle_system
                .after(crate::layer1::day_night::update_day_night_cycle_system),
            update_bioluminescence_system
                .after(crate::layer1::day_night::update_day_night_cycle_system),
            crate::layer1::flora::lumiflora_bloom_system
                .after(crate::layer1::day_night::update_day_night_cycle_system),
            crate::layer1::flora::apply_bio_rhythm_aura
                .after(crate::layer1::flora::lumiflora_bloom_system),
            crate::layer1::pop::reset_speed_system.before(apply_lighting_penalties_system),
            crate::layer1::tech::event_horizon_tap::apply_time_dilation_system
                .after(crate::layer1::pop::reset_speed_system)
                .before(apply_lighting_penalties_system),
            crate::layer1::tech::apply_cognitive_overclocking_system
                .after(crate::layer1::pop::reset_speed_system)
                .before(apply_lighting_penalties_system),
            crate::layer1::tech::process_neural_burnout_system,
            crate::layer1::tech::check_burnout_threshold_system,
            crate::layer1::tech::machine_awakening::process_bot_sentience,
            crate::layer1::tech::machine_awakening::apply_awakened_needs,
            update_lighting_system
                .after(process_start_plan_system)
                .after(crate::layer1::day_night::update_ambient_light_from_cycle_system)
                .after(update_bioluminescence_system),
            crate::layer1::environment::light_pollution::calculate_sky_glow_system
                .after(update_lighting_system),
            crate::layer1::environment::light_pollution::apply_light_pollution_system
                .after(crate::layer1::environment::light_pollution::calculate_sky_glow_system),
            crate::layer1::integration::nocturnal_aggression_bridge_system
                .after(crate::layer1::environment::light_pollution::apply_light_pollution_system),
        )
            .in_set(Layer1SystemSet::Execution),
    );

    schedule.add_systems(
        (
            apply_lighting_penalties_system.after(update_lighting_system),
            crate::layer1::environment::ignition::process_ignition
                .after(crate::layer1::physics::hit_stop::hit_stop_system),
            crate::layer1::architecture::resonant_architecture::apply_resonant_architecture_system,
            apply_weather_effects_system.after(apply_lighting_penalties_system),
            crate::layer1::nature::psychoactive_weather::apply_weather_moodlets_system,
            crate::layer1::nature::psychoactive_weather::process_euphoria_effects_system
                .after(crate::layer1::nature::psychoactive_weather::apply_weather_moodlets_system),
            crate::layer1::nature::mutagenic_rain::apply_mutagenic_rain_system
                .after(apply_weather_effects_system),
            crate::layer1::nature::mutagenic_rain::clear_mutation_immunity_system
                .after(crate::layer1::nature::mutagenic_rain::apply_mutagenic_rain_system),
            apply_quirk_modifiers_system
                .after(apply_lighting_penalties_system)
                .after(apply_weather_effects_system),
            crate::layer1::chemical::apply_chemical_speed_modifiers_system,
            crate::layer1::cryo_shock::apply_cryo_debuff_system
                .after(crate::layer1::pop::reset_speed_system)
                .before(crate::layer1::chemical::apply_chemical_speed_modifiers_system)
                .after(apply_quirk_modifiers_system),
            #[cfg(feature = "nova")]
            crate::layer1::observer::observer_reaction_system
                .after(apply_lighting_penalties_system),
            #[cfg(feature = "nova")]
            crate::layer1::machine_consciousness::consciousness_effect_system
                .after(crate::layer1::pop::reset_speed_system),
            crate::layer1::physics::hit_stop::hit_stop_system.after(process_start_plan_system),
            crate::layer1::sonic_suppression::sonic_suppression_system,
            crate::layer1::integration::sonic_turret_noise_bridge_system
                .after(crate::layer1::sonic_suppression::sonic_suppression_system),
            crate::layer1::sonic_suppression::apply_nausea_effects_system
                .after(crate::layer1::sonic_suppression::sonic_suppression_system),
            crate::layer1::combat::combat_cooldown_system.after(process_start_plan_system),
        )
            .in_set(Layer1SystemSet::Execution),
    );

    schedule.add_systems(
        (
            crate::layer1::mind::temporal_fugue::evaluate_fugue_state_system
                .before(work_execution_system),
            crate::layer1::mind::temporal_fugue::fugue_completion_system
                .after(work_execution_system),
        )
            .in_set(Layer1SystemSet::Execution),
    );

    schedule.add_systems(
        (
            crate::layer1::logistics::glider::update_glider_movement_system
                .after(crate::layer1::pop::reset_speed_system),
            crate::layer1::logistics::mass_driver::mass_driver_launch_system,
            crate::layer1::logistics::mass_driver::package_arrival_system,
            crate::layer1::logistics::commute::process_orbital_commutes
                .after(process_start_plan_system),
        )
            .in_set(Layer1SystemSet::Execution),
    );

    schedule.add_systems(
        (
            crate::layer1::core::integration::gravity_plating_power_bridge_system,
            crate::layer1::physics::gravity_plating::monitor_gravity_generator_power_system
                .after(crate::layer1::core::integration::gravity_plating_power_bridge_system),
            crate::layer1::physics::gravity_plating::update_tile_gravity,
            crate::layer1::physics::gravity_plating::update_pop_orientation,
            crate::layer1::physics::gravity_plating::apply_falling_mechanics,
            crate::layer1::physics::gravity_plating::apply_zero_g_movement_system.after(
                crate::layer1::physics::gravity_plating::monitor_gravity_generator_power_system,
            ),
            crate::layer1::physics::gravity_plating::apply_drifting_movement_system
                .after(crate::layer1::physics::gravity_plating::apply_zero_g_movement_system),
        )
            .in_set(Layer1SystemSet::Execution),
    );

    schedule.add_systems(
        (
            movement_system
                .after(apply_quirk_modifiers_system)
                .after(crate::layer1::fauna::fauna_behavior_system)
                .after(crate::layer1::physics::hit_stop::hit_stop_system)
                .after(crate::layer1::physics::gravity_plating::apply_zero_g_movement_system),
            crate::layer1::infrastructure::transit_toll_system.after(movement_system),
            handle_direct_movement.after(crate::layer1::physics::hit_stop::hit_stop_system),
            crate::layer1::crowding::crowding_accumulation_system.after(movement_system),
            crate::layer1::artifacts::apply_artifact_auras_system.after(movement_system),
            arrival_handler_system.after(movement_system),
            crate::layer1::customs::vetting_work_system.after(arrival_handler_system),
            crate::layer1::hobby::execute_hobby_system.after(arrival_handler_system),
            crate::layer1::the_lottery::execute_lottery_system.after(arrival_handler_system),
            crate::layer1::husbandry::tame_execution_system.after(arrival_handler_system),
            crate::layer1::turret::turret_fire_system.after(combat_execution_system),
            crate::layer1::law::justice::warden_execution_system.after(combat_execution_system),
            crate::layer1::law::predictive_policing::pre_crime_execution_system
                .after(combat_execution_system),
            crate::layer1::the_lottery::execute_lottery_system.after(arrival_handler_system),
            crate::layer1::hygiene::shower_use_system.after(work_execution_system),
            crate::layer1::hum::execute_listen_to_hum_system.after(arrival_handler_system),
            crate::layer1::clutter::clutter_cleaning_system.after(arrival_handler_system),
            crate::layer1::tech::ghost_code::purge_execution_system.after(arrival_handler_system),
            crate::layer1::tech::martyrs_engine::attune_engine_system.after(arrival_handler_system),
            crate::layer1::execution::mining::harmonic_mining_system.after(arrival_handler_system),
        )
            .in_set(Layer1SystemSet::Execution),
    );

    schedule.add_systems(
        (
            crate::layer1::petrification::petrification_exposure_system,
            crate::layer1::petrification::petrification_progression_system,
            crate::layer1::petrification::petrification_transformation_system,
        )
            .in_set(Layer1SystemSet::Execution),
    );

    schedule.add_systems(
        (
            crate::layer1::tinkering::obsessive_optimization_system,
            crate::layer1::execution::vandalize_execution_system.after(arrival_handler_system),
            crate::layer1::pop_doppelganger::sabotage_system.after(work_execution_system),
            crate::layer1::drone::check_drone_connection.after(arrival_handler_system),
            crate::layer1::drone::process_feral_drones
                .after(crate::layer1::drone::check_drone_connection),
            crate::layer1::drone::process_charge_system.after(arrival_handler_system),
            update_social_class_system.after(arrival_handler_system),
            class_friction_system.after(update_social_class_system),
            haul_system.after(arrival_handler_system),
        )
            .in_set(Layer1SystemSet::Execution),
    );

    schedule.add_systems(
        (
            conveyor_system.after(haul_system),
            crate::layer1::logistics::mycelial::mycelial_transport_system.after(conveyor_system),
            crate::layer1::logistics::mycelial::mycelial_upkeep_system
                .after(crate::layer1::logistics::mycelial::mycelial_transport_system),
            crate::layer1::logistics::mycelial::mycelial_contamination_system
                .after(crate::layer1::logistics::mycelial::mycelial_upkeep_system),
            crate::layer1::logistics::conveyor::inserter_system.after(conveyor_system),
            crate::layer1::logistics::conveyor::hopper_system
                .after(crate::layer1::logistics::conveyor::inserter_system),
            crate::layer1::logistics::pneumatic::tube_network_system.after(haul_system),
            crate::layer1::logistics::pneumatic::tube_transport_system
                .after(crate::layer1::logistics::pneumatic::tube_network_system),
            crate::layer1::nanite_fabrication::nanite_fabrication_system
                .after(arrival_handler_system),
            crate::layer1::nanite_fabrication::grey_goo_replication_system
                .after(crate::layer1::nanite_fabrication::nanite_fabrication_system),
            crate::layer1::integration::nanite_breach_goo_bridge
                .after(crate::layer1::nanite_fabrication::nanite_fabrication_system)
                .before(crate::layer1::nanite_fabrication::grey_goo_replication_system),
            crate::layer1::integration::nanite_breach_chronicle_bridge
                .after(crate::layer1::nanite_fabrication::nanite_fabrication_system),
            crate::layer1::integration::nanite_breach_storm_bridge
                .after(crate::layer1::nanite_fabrication::nanite_fabrication_system),
            process_scan_system.after(arrival_handler_system),
            update_cabin_fever_system.after(movement_system),
            crate::layer1::social::empty_room::visit_sanctuary_system.after(movement_system),
            crate::layer1::tech::hypno_learning::hypno_sleep_system.after(arrival_handler_system),
            crate::layer1::tech::hypno_learning::wake_up_hypno_system
                .after(process_start_plan_system),
            crate::layer1::biology::symbiotic_parasite::apply_parasite_buffs_system
                .after(work_execution_system),
            crate::layer1::biology::symbiotic_parasite::apply_parasite_health_drain_system
                .after(work_execution_system),
        )
            .in_set(Layer1SystemSet::Execution),
    );

    schedule.add_systems(
        (
            crate::layer1::entities::swarm_intelligence::update_drone_clusters,
            crate::layer1::entities::swarm_intelligence::update_drone_behavior
                .after(crate::layer1::entities::swarm_intelligence::update_drone_clusters),
        )
            .in_set(Layer1SystemSet::Execution),
    );

    schedule.add_systems(
        (
            crate::layer1::flora::consume_silent_flora_system.after(movement_system),
            crate::layer1::fauna::suppress_fauna_system.after(movement_system),
        )
            .in_set(Layer1SystemSet::Execution),
    );

    schedule.add_systems(
        (
            crate::layer1::agony_extract::process_agony_extract_harvest_system
                .after(work_execution_system),
            crate::layer1::temporal_chamber::temporal_chamber_energy_system,
            crate::layer1::core::integration::temporal_chamber_power_bridge_system
                .after(crate::layer1::temporal_chamber::temporal_chamber_energy_system),
        )
            .in_set(Layer1SystemSet::Execution),
    );
    schedule.add_systems(
        (
            crate::layer1::tech::hypno_learning::update_mental_fog_system.after(movement_system),
            crate::layer1::culture::ancestral_graves::visit_grave_system,
            crate::layer1::culture::ancestral_graves::sacrilege_morale_system,
            crate::layer1::culture::linguistics::apply_linguistic_drift
                .after(arrival_handler_system),
            crate::layer1::psychology::dreaming_sickness::spread_dreaming_sickness,
            crate::layer1::psychology::dreaming_sickness::dreaming_sickness_effects,
            crate::layer1::psychology::dreaming_sickness::spontaneous_sleep,
        )
            .in_set(Layer1SystemSet::Execution),
    );

    schedule.add_systems(
        (
            wild_child_system.after(movement_system),
            update_erosion_system.after(movement_system),
            crate::layer1::particles::particle_physics_system.after(movement_system),
            crate::layer1::particles::particle_system
                .after(crate::layer1::particles::particle_physics_system),
            infiltration_system.after(movement_system),
            discovery_system.after(process_scan_system),
        )
            .in_set(Layer1SystemSet::Execution),
    );

    schedule.add_systems(
        (
            crate::layer1::shipbreaking::spawn_crashed_ship_system.after(process_start_plan_system),
            crate::layer1::shipbreaking::mine_system.after(arrival_handler_system),
            crate::layer1::nature::biosphere_inversion::deep_crust_breach_system
                .after(crate::layer1::shipbreaking::mine_system),
            crate::layer1::shipbreaking::hull_destroyed_system
                .after(crate::layer1::shipbreaking::mine_system),
            crate::layer1::grafting::process_grafting,
            crate::layer1::void_sirens::apply_siren_obsession.after(process_start_plan_system),
            crate::layer1::void_sirens::handle_obsessed_jobs
                .after(crate::layer1::void_sirens::apply_siren_obsession),
            crate::layer1::administration::edicts::handle_policy_toggle_system,
            crate::layer1::administration::edicts::handle_hack_hub_system,
            crate::layer1::law::orphaned_edict::orphaned_edict_enforcement_system,
            crate::layer1::law::aesthetic_edict::enforce_aesthetic_edict_system,
            crate::layer1::administration::malicious_compliance::malicious_compliance_system,
        )
            .in_set(Layer1SystemSet::Execution),
    );

    schedule.add_systems(
        (
            crate::layer1::heirloom_tool::process_pop_death_for_heirloom,
            crate::layer1::heirloom_tool::process_heirloom_equip,
        )
            .in_set(Layer1SystemSet::Execution),
    );
    schedule.add_systems((
        crate::layer1::core::integration::phantom_commutes_bridge_system,
        (
            crate::layer1::execution::phantom_commutes::apply_phantom_commute_system
                .before(movement_system),
            crate::layer1::execution::phantom_commutes::remove_resolved_phantom_commute_system
                .after(movement_system),
        )
            .in_set(Layer1SystemSet::Execution),
    ));

    schedule.add_systems(
        (
            // Spec 1379: Desire Dust roads. Exclusive (World) systems.
            crate::layer1::desire_dust::accumulate_desire_dust,
            crate::layer1::desire_dust::decay_desire_dust,
            crate::layer1::desire_dust::check_road_sentience,
            crate::layer1::desire_dust::apply_desire_dust_speed
                .after(crate::layer1::pop::reset_speed_system)
                .before(movement_system),
            crate::layer1::desire_dust::road_mind_pheromone_system
                .before(crate::layer1::execution::phantom_commutes::apply_phantom_commute_system),
        )
            .in_set(Layer1SystemSet::Execution),
    );

    schedule.add_systems(
        (
            crate::layer1::tech::temporal_smuggling::open_rift_system,
            crate::layer1::tech::temporal_smuggling::pay_temporal_debt_system,
            crate::layer1::tech::temporal_smuggling::check_temporal_debts_system,
            crate::layer1::core::integration::temporal_smuggling_chronicle_bridge,
        )
            .in_set(Layer1SystemSet::Execution),
    );

    schedule.add_systems(
        crate::layer1::improvised_tools::evaluate_tool_fallback_system
            .in_set(Layer1SystemSet::Execution),
    );
    schedule.add_systems(
        (
            crate::layer1::heroic_acts::activate_heroic_act_system,
            crate::layer1::heroic_acts::resolve_heroic_acts_system,
        )
            .chain()
            .in_set(Layer1SystemSet::Execution),
    );
    schedule.add_systems(
        (
            crate::layer1::cassandra_syndrome::generate_doomsday_warning,
            crate::layer1::cassandra_syndrome::handle_ignored_warning,
            crate::layer1::cassandra_syndrome::validate_prophecy,
        )
            .chain()
            .in_set(Layer1SystemSet::Execution),
    );
    schedule.add_systems(
        crate::layer1::tech::symbiotic_data_weavers::process_data_forest_system
            .in_set(Layer1SystemSet::Execution),
    );
    schedule.add_systems(
        crate::layer1::core::integration::magnetic_reversal_chronicle_bridge
            .in_set(Layer1SystemSet::Execution),
    );
    schedule.add_systems(
        crate::layer1::core::integration::long_night_chronicle_bridge
            .in_set(Layer1SystemSet::Execution),
    );

    // Spec 275 Architectural Sabotage: rival-infiltrated construction crews
    // plant sabotage points; armed countdown -> catastrophic failure.
    schedule.add_systems(
        (
            crate::layer1::architecture::construction_sabotage::insert_sabotage_on_completion_system,
            crate::layer1::architecture::construction_sabotage::tick_sabotage_system
                .after(crate::layer1::architecture::construction_sabotage::insert_sabotage_on_completion_system),
            crate::layer1::architecture::construction_sabotage::handle_building_failure_system
                .after(crate::layer1::architecture::construction_sabotage::tick_sabotage_system),
        )
            .in_set(super::Layer1SystemSet::Execution),
    );

    // Spec 277 Orbital Megastructure Deorbiting: warning countdown, tether
    // catch, catastrophic impact. Separate add_systems call (not the shared
    // tuple) to stay clear of the IntoSystemConfigs arity limit.
    schedule.add_systems(
        (
            crate::layer1::disasters::deorbit::trigger_deorbit_system,
            crate::layer1::disasters::deorbit::tick_deorbit_system
                .after(crate::layer1::disasters::deorbit::trigger_deorbit_system),
        )
            .in_set(super::Layer1SystemSet::Execution),
    );
}
