//! # Knowledge & Technology System
//!
//! This module implements the research and technology progression system for the colony.
//! Unlike traditional "Tech Trees", the system in SCALE is based on a **Data Economy**.
//!
//! ## Core Concepts
//!
//! ### 1. Knowledge (Currency)
//! *   Generated by Pops working at a [`Library`].
//! *   Stored in [`ColonyResources`](crate::layer1::resources::ColonyResources).
//! *   Used to "buy" new technologies via [`unlock_tech`].
//!
//! ### 2. Data Capacity (Limit)
//! *   Every active technology consumes **Data Storage** (measured in TB).
//! *   Capacity is provided by [`BuildingType::ServerBank`](crate::layer1::building::BuildingType::ServerBank)
//!     and the [`BuildingType::Lander`](crate::layer1::building::BuildingType::Lander).
//! *   If `Used Capacity > Total Capacity`, the system enters a **Corruption** state.
//!
//! ### 3. Corruption
//! *   When capacity is exceeded, the system automatically "corrupts" (disables) the most expensive technologies
//!     to free up space.
//! *   Corrupted techs provide no benefits until capacity is restored and they are auto-repaired.
//! *   This creates a "Soft Cap" on tech progress—you can research everything, but you can't *use*
//!     everything simultaneously without massive server infrastructure.
//!
//! ### 4. Memetic Hazards
//! *   Some technologies (like `Tech::VoidWhispers`) are **Hazardous**.
//! *   Researching them triggers an immediate infection event (see [`crate::layer1::memetics`]).
//! *   This represents the danger of uncovering "Forbidden Knowledge".

#![allow(clippy::collapsible_if)]
use crate::layer1::actions::{AssignedTo, AssignmentType};
use crate::layer1::factions::{FactionMember, FactionState, Factions};
use crate::layer1::map::{CameraTarget, GridPosition, ScreenShake};
use crate::layer1::particles::spawn_confetti;
use crate::layer1::resources::ColonyResources;
use crate::layer1::GlobalHitStop;
use crate::shared::log::MessageLog;
use bevy_ecs::prelude::*;
use std::collections::HashMap;

use strum_macros::EnumIter;

/// Available technologies in the tech tree.
///
/// Technologies are flat (no hard dependencies) but tiered by cost.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, EnumIter)]
pub enum Tech {
    /// Allows construction of advanced stone buildings.
    Masonry,
    /// Allows working with metal (Smelter).
    MetalWorking,
    /// Allows advanced social buildings (Tavern).
    SocialStructures,
    /// Allows construction of the Observatory.
    Astronomy,
    /// Allows construction of Hydroponics Bays.
    Hydroponics,
    /// Allows active defense (Trash Cannon, Militia).
    Militia,
    /// Allows advanced medical facilities (Hospital, `CryoPod`).
    Medical,
    /// Allows harnessing atmospheric energy (`AuroralCollector`).
    Electromagnetism,
    /// Unlocks dangerous forbidden knowledge (Memetic Hazards).
    VoidWhispers,
    /// Unlocks planetary engineering (`AtmosphericProcessor`).
    Terraforming,
}

impl Tech {
    /// Returns true if this technology carries a Memetic Hazard risk.
    ///
    /// Researching this will trigger an immediate [`crate::layer1::memetics::MemeticCarrier`] infection
    /// on a random researcher.
    #[must_use]
    pub const fn is_hazardous(&self) -> bool {
        matches!(self, Self::VoidWhispers)
    }

    /// Returns the Knowledge cost to unlock this technology.
    #[must_use]
    pub const fn cost(&self) -> f32 {
        match self {
            Self::Masonry => 10.0,
            Self::MetalWorking => 20.0,
            Self::SocialStructures => 15.0,
            Self::Astronomy => 50.0,
            Self::Hydroponics => 30.0,
            Self::Militia => 25.0,
            Self::Medical => 40.0,
            Self::Electromagnetism => 35.0,
            Self::VoidWhispers => 100.0,
            Self::Terraforming => 75.0,
        }
    }

    /// Returns the human-readable name of the technology.
    #[must_use]
    pub const fn label(&self) -> &str {
        match self {
            Self::Masonry => "Masonry",
            Self::MetalWorking => "Metal Working",
            Self::SocialStructures => "Social Structures",
            Self::Astronomy => "Astronomy",
            Self::Hydroponics => "Hydroponics",
            Self::Militia => "Militia",
            Self::Medical => "Medical",
            Self::Electromagnetism => "Electromagnetism",
            Self::VoidWhispers => "Void Whispers",
            Self::Terraforming => "Terraforming",
        }
    }

    /// Returns the description of the technology.
    #[must_use]
    pub const fn description(&self) -> &str {
        match self {
            Self::Masonry => {
                "Unlocks advanced stone construction techniques, allowing for sturdier and more impressive structures."
            }
            Self::MetalWorking => {
                "Enables the processing of ores into refined metals, a crucial step for industrialization."
            }
            Self::SocialStructures => {
                "Develops social gathering places and artistic expression to improve colony morale."
            }
            Self::Astronomy => {
                "Unlocks the secrets of the stars, enabling advanced navigation and research."
            }
            Self::Hydroponics => {
                "Advanced farming techniques that allow crops to be grown indoors without soil."
            }
            Self::Militia => {
                "Organizes colonists into a defense force to protect the colony from threats."
            }
            Self::Medical => {
                "Advanced medical knowledge and facilities to treat injuries and diseases."
            }
            Self::Electromagnetism => {
                "Harnesses the power of electromagnetic fields for energy generation."
            }
            Self::VoidWhispers => {
                "Forbidden knowledge from the void. Offers great power at a terrible cost."
            }
            Self::Terraforming => "Technologies to modify the planetary atmosphere and climate.",
        }
    }

    /// Returns the data storage cost (in TB) required to maintain this technology.
    ///
    /// If total storage cost exceeds capacity, techs will become [`TechStatus::Corrupted`].
    #[must_use]
    pub const fn storage_cost(&self) -> f32 {
        match self {
            Self::Masonry => 5.0,
            Self::MetalWorking | Self::Militia => 10.0,
            Self::SocialStructures | Self::Hydroponics | Self::Electromagnetism => 15.0,
            Self::Astronomy | Self::Medical => 20.0,
            Self::VoidWhispers => 50.0,
            Self::Terraforming => 30.0,
        }
    }
}

/// Status of a researched technology.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TechStatus {
    /// Technology is fully functional.
    Active,
    /// Technology is corrupted due to data loss/capacity issues.
    /// It behaves as if it is **locked**.
    Corrupted,
}

/// Resource tracking the state of technology research.
///
/// This resource holds the map of researched technologies and manages the Data Capacity budget.
///
/// # Examples
///
/// Checking if a tech is available:
/// ```
/// use scale::layer1::tech::{Tech, TechState};
///
/// let state = TechState::default();
/// // state.unlock(Tech::Masonry); // Assuming setup
///
/// if state.is_unlocked(Tech::Masonry) {
///     // Build stone wall
/// }
/// ```
#[derive(Resource, Default, Debug)]
pub struct TechState {
    /// The set of unlocked technologies and their status.
    pub techs: HashMap<Tech, TechStatus>,
    /// Total data capacity available (TB).
    pub total_capacity: f32,
    /// Currently used data capacity (TB).
    pub used_capacity: f32,
}

impl TechState {
    /// Checks if a specific technology is unlocked AND active.
    /// Returns false if the tech is not researched or is Corrupted.
    #[must_use]
    pub fn is_unlocked(&self, tech: Tech) -> bool {
        self.is_active(tech)
    }

    /// Checks if a specific technology has been researched (Active or Corrupted).
    #[must_use]
    pub fn is_researched(&self, tech: Tech) -> bool {
        self.techs.contains_key(&tech)
    }

    /// Checks if a specific technology is fully active.
    #[must_use]
    pub fn is_active(&self, tech: Tech) -> bool {
        self.techs.get(&tech) == Some(&TechStatus::Active)
    }

    /// Unlocks a technology (forces Active).
    /// Used by existing tests/code that bypass cost checks.
    pub fn unlock(&mut self, tech: Tech) {
        self.techs.insert(tech, TechStatus::Active);
        self.update_corruption(); // Recalculate used capacity
    }

    /// Attempts to unlock a technology if capacity allows.
    pub fn try_unlock(&mut self, tech: Tech) -> bool {
        if self.techs.contains_key(&tech) {
            return true;
        }

        if self.used_capacity + tech.storage_cost() > self.total_capacity {
            return false;
        }

        self.techs.insert(tech, TechStatus::Active);
        self.used_capacity += tech.storage_cost();
        true
    }

    /// Helper for tests to force a specific status.
    #[cfg(test)]
    pub fn force_unlock(&mut self, tech: Tech, status: TechStatus) {
        self.techs.insert(tech, status);
        self.update_corruption();
    }

    /// Returns the status of a tech, if unlocked.
    #[cfg(test)]
    pub fn status(&self, tech: Tech) -> TechStatus {
        *self.techs.get(&tech).unwrap_or(&TechStatus::Active)
    }

    /// Updates corruption state based on capacity.
    ///
    /// If `used > total`, it corrupts the **most expensive** active techs first until
    /// usage drops below capacity.
    ///
    /// If `used <= total`, it attempts to restore **cheapest** corrupted techs first.
    pub fn update_corruption(&mut self) {
        // Calculate used capacity from active techs
        let active_usage: f32 = self
            .techs
            .iter()
            .filter(|(_, status)| **status == TechStatus::Active)
            .map(|(t, _)| t.storage_cost())
            .sum();

        if active_usage > self.total_capacity {
            // Over capacity! Corrupt the MOST EXPENSIVE techs first.
            let mut active_techs: Vec<Tech> = self
                .techs
                .iter()
                .filter(|(_, s)| **s == TechStatus::Active)
                .map(|(t, _)| *t)
                .collect();

            active_techs.sort_by(|a, b| {
                b.storage_cost()
                    .partial_cmp(&a.storage_cost())
                    .unwrap_or(std::cmp::Ordering::Equal)
            });

            let mut current_usage = active_usage;
            for tech in active_techs {
                if current_usage <= self.total_capacity {
                    break;
                }

                self.techs.insert(tech, TechStatus::Corrupted);
                current_usage -= tech.storage_cost();
            }
        } else {
            // Auto-repair if capacity allows
            let mut corrupted_techs: Vec<Tech> = self
                .techs
                .iter()
                .filter(|(_, s)| **s == TechStatus::Corrupted)
                .map(|(t, _)| *t)
                .collect();

            // Sort by cost asc (restore cheap first)
            corrupted_techs.sort_by(|a, b| {
                a.storage_cost()
                    .partial_cmp(&b.storage_cost())
                    .unwrap_or(std::cmp::Ordering::Equal)
            });

            let mut current_usage = active_usage;
            for tech in corrupted_techs {
                if current_usage + tech.storage_cost() <= self.total_capacity {
                    self.techs.insert(tech, TechStatus::Active);
                    current_usage += tech.storage_cost();
                }
            }
        }

        // Final update of used_capacity
        self.used_capacity = self
            .techs
            .iter()
            .filter(|(_, status)| **status == TechStatus::Active)
            .map(|(t, _)| t.storage_cost())
            .sum();
    }
}

/// Component marker for Library buildings.
///
/// Libraries allow Pops assigned as `LibraryWorker` to generate Knowledge.
#[derive(Component, Default)]
pub struct Library;

/// Component providing data storage capacity.
///
/// Attached to buildings like `ServerBank` and `Lander`.
/// The sum of all `capacity` fields on active (powered) entities determines the colony's
/// `TechState::total_capacity`.
#[derive(Component, Default)]
pub struct DataStorage {
    /// Capacity in Terabytes (TB).
    pub capacity: f32,
}

/// Attempts to unlock a technology using Knowledge.
///
/// # Logic
///
/// 1.  **Check Cost**: Pop must have enough `resources.knowledge`.
/// 2.  **Check Capacity**: `TechState` must have room for the `storage_cost`.
/// 3.  **Deduct & Unlock**: Remove knowledge, add to TechState.
/// 4.  **Side Effects**:
///     *   Triggers "Juice" (Screen Shake, Hit Stop, Particles).
///     *   If `Tech::is_hazardous`, infects a researcher.
///
/// Returns `true` if successful.
pub fn unlock_tech(world: &mut World, tech: Tech) -> bool {
    // Check if already researched (even if Corrupted)?
    if world.resource::<TechState>().is_researched(tech) {
        return true;
    }

    let cost = tech.cost();
    let can_afford_resources = {
        let res = world.resource::<ColonyResources>();
        res.knowledge >= cost
    };

    if !can_afford_resources {
        return false;
    }

    // Try to unlock (checking capacity)
    // Note: We need to borrow TechState mutably
    let unlocked = world.resource_mut::<TechState>().try_unlock(tech);

    if unlocked {
        world.resource_mut::<ColonyResources>().knowledge -= cost;
        if let Some(mut log) = world.get_resource_mut::<MessageLog>() {
            log.add(format!("Researched: {}", tech.label()));
        }

        // Ludwig: Juice for Tech Unlock!
        if let Some(mut shake) = world.get_resource_mut::<ScreenShake>() {
            shake.trigger(0.5);
        }
        if let Some(mut hit_stop) = world.get_resource_mut::<GlobalHitStop>() {
            hit_stop.trigger(4);
        }
        // Spawn confetti at camera center
        let (cx, cy) = world
            .get_resource::<CameraTarget>()
            .map_or((10, 10), |target| {
                #[allow(clippy::cast_possible_truncation)]
                (target.x as i32, target.y as i32)
            });
        spawn_confetti(world, GridPosition { x: cx, y: cy });

        // Handle Memetic Hazards
        if tech.is_hazardous() {
            // Find a researcher to infect
            use crate::layer1::memetics::MemeticCarrier;
            use rand::seq::IteratorRandom;

            let mut rng = rand::thread_rng();

            // Correction: `query.iter(world)` yields components. I need Entity ID.
            let mut query = world.query::<(Entity, &AssignedTo)>();
            let candidates: Vec<Entity> = query
                .iter(world)
                .filter(|(_, a)| a.assignment_type == AssignmentType::LibraryWorker)
                .map(|(e, _)| e)
                .collect();

            if let Some(victim) = candidates.into_iter().choose(&mut rng) {
                world.entity_mut(victim).insert(MemeticCarrier);
                if let Some(mut log) = world.get_resource_mut::<MessageLog>() {
                    log.add(
                        "WARNING: A researcher has been infected by Memetic Hazards!".to_string(),
                    );
                }
            }
        }

        true
    } else {
        if let Some(mut log) = world.get_resource_mut::<MessageLog>() {
            log.add(format!(
                "Failed to research {}: Insufficient Data Capacity",
                tech.label()
            ));
        }
        false
    }
}

/// Generates knowledge based on pops working at Libraries.
///
/// # Formula
///
/// `Knowledge Gain = 0.01 * Workers` per tick.
///
/// *   **Strikes**: Workers in a striking faction produce 0 knowledge.
/// *   **Efficiency**: Currently flat rate, but could be modified by Intelligence/Traits later.
pub fn process_research_system(
    pops: Query<(&AssignedTo, Option<&FactionMember>)>,
    libraries: Query<Entity, With<Library>>,
    mut resources: ResMut<ColonyResources>,
    factions: Option<Res<Factions>>,
    bloat_query: Query<&self::legacy_code::SystemBloat>,
    archive: Option<Res<self::infinite_archive::Archive>>,
    mut library_workers: Local<bevy::utils::HashMap<Entity, u32>>,
) {
    // ⚡ Bolt Optimization: Uses `Local` and `bevy::utils::HashMap` to eliminate frame-by-frame heap allocations and speed up entity hashing.
    library_workers.clear();

    for (assignment, member_opt) in &pops {
        if assignment.assignment_type == AssignmentType::LibraryWorker {
            if let Some(factions) = &factions {
                if let Some(member) = member_opt {
                    if let Some(fid) = member.faction_id {
                        if factions
                            .get(fid)
                            .is_some_and(|d| d.state == FactionState::Striking)
                        {
                            continue;
                        }
                    }
                }
            }

            *library_workers.entry(assignment.entity).or_insert(0) += 1;
        }
    }

    let mut total_knowledge_gained = 0.0;

    for library_entity in &libraries {
        if let Some(&workers) = library_workers.get(&library_entity) {
            #[allow(clippy::cast_precision_loss)]
            let knowledge_gain = 0.01 * workers as f32;
            total_knowledge_gained += knowledge_gain;
        }
    }

    // Apply Legacy Code Bloat Efficiency
    if let Ok(bloat) = bloat_query.get_single() {
        total_knowledge_gained *= bloat.efficiency();
    }

    // Apply Infinite Archive Efficiency (Spec 248)
    if let Some(archive) = archive {
        total_knowledge_gained *= archive.efficiency_multiplier;
    }

    if total_knowledge_gained > 0.0 {
        resources.knowledge =
            (resources.knowledge + total_knowledge_gained).clamp(0.0, resources.max_knowledge);
    }
}

/// Updates global tech capacity based on powered servers.
///
/// Scans for all entities with `DataStorage` and `PowerConsumer`.
/// If power is active (or missing), adds capacity to `TechState::total_capacity`.
/// Triggers `update_corruption` to handle drops in capacity.
pub fn update_tech_capacity_system(
    mut tech_state: ResMut<TechState>,
    query: Query<(&DataStorage, Option<&crate::layer1::energy::PowerConsumer>)>,
) {
    let total_cap: f32 = query
        .iter()
        .filter(|(_, power)| power.is_none_or(|p| p.active))
        .map(|(storage, _)| storage.capacity)
        .sum();

    tech_state.total_capacity = total_cap;
    tech_state.update_corruption();
}

pub mod ego_machine;
pub use ego_machine::*;

#[cfg(test)]
mod tests {
    use super::*;
    use crate::layer1::building::{try_place_building, BuildingType};
    use crate::layer1::resources::ColonyResources;
    use crate::layer1::terrain::{TerrainGrid, TerrainType};

    #[test]
    fn test_resources_knowledge_fields() {
        let res = ColonyResources::default();
        assert!(res.knowledge.abs() < f32::EPSILON);
        assert!((res.max_knowledge - 100.0).abs() < f32::EPSILON);
    }

    #[test]
    fn test_tech_enum_exists() {
        // Just verifying variants exist
        let _ = Tech::Masonry;
        let _ = Tech::MetalWorking;
        let _ = Tech::SocialStructures;
    }

    #[test]
    fn test_tech_costs() {
        assert!((Tech::Masonry.cost() - 10.0).abs() < f32::EPSILON);
        assert!((Tech::MetalWorking.cost() - 20.0).abs() < f32::EPSILON);
    }

    #[test]
    fn test_tech_state_starts_empty() {
        let state = TechState::default();
        assert!(!state.is_unlocked(Tech::Masonry));
        assert!(!state.is_unlocked(Tech::MetalWorking));
    }

    #[test]
    fn test_unlock_tech_success() {
        let mut world = World::new();
        let state = TechState {
            total_capacity: 100.0,
            ..Default::default()
        };
        world.insert_resource(state);
        world.insert_resource(MessageLog::default());
        world.insert_resource(ColonyResources {
            knowledge: 20.0,
            ..Default::default()
        });

        let success = unlock_tech(&mut world, Tech::Masonry);

        assert!(success);
        assert!(world.resource::<TechState>().is_unlocked(Tech::Masonry));

        let res = world.resource::<ColonyResources>();
        assert!((res.knowledge - 10.0).abs() < f32::EPSILON); // Cost 10
    }

    #[test]
    fn test_unlock_tech_insufficient_funds() {
        let mut world = World::new();
        world.insert_resource(TechState::default());
        world.insert_resource(ColonyResources {
            knowledge: 5.0, // Need 10
            ..Default::default()
        });

        let success = unlock_tech(&mut world, Tech::Masonry);

        assert!(!success);
        assert!(!world.resource::<TechState>().is_unlocked(Tech::Masonry));
        assert!((world.resource::<ColonyResources>().knowledge - 5.0).abs() < f32::EPSILON);
    }

    #[test]
    fn test_building_requires_tech() {
        assert_eq!(BuildingType::Housing.required_tech(), None); // Basic
        assert_eq!(
            BuildingType::Smelter.required_tech(),
            Some(Tech::MetalWorking)
        );
        assert_eq!(
            BuildingType::Tavern.required_tech(),
            Some(Tech::SocialStructures)
        );
    }

    #[test]
    fn test_placement_fails_if_tech_locked() {
        let mut world = World::new();
        world.insert_resource(TechState::default());
        world.insert_resource(MessageLog::default());
        world.insert_resource(ColonyResources {
            wood: 100.0,
            stone: 100.0,
            ..Default::default()
        }); // Plenty of resources

        // Setup Grid
        world.insert_resource(TerrainGrid {
            width: 10,
            height: 10,
            tiles: vec![TerrainType::Grass; 100],
        });
        world.insert_resource(crate::layer1::building::OccupiedTiles::default());

        // Try to place Smelter (needs MetalWorking)
        let success = try_place_building(&mut world, 5, 5, BuildingType::Smelter);

        assert!(!success);
    }

    #[test]
    fn test_tech_status_fallback_to_active() {
        let state = TechState::default();
        // Since it's not in the map, it should unwrap_or to TechStatus::Active
        assert_eq!(state.status(Tech::Masonry), TechStatus::Active);
    }

    #[test]
    fn test_tech_corruption_sort_stability() {
        let mut state = TechState {
            total_capacity: 0.0, // Force corruption
            ..Default::default()
        };
        // MetalWorking and Militia both cost 10.0 storage.
        // We will insert them and let `update_corruption` sort and corrupt them.
        // The unwrap_or handles NaNs if they ever appeared in the hardcoded costs.
        state.techs.insert(Tech::MetalWorking, TechStatus::Active);
        state.techs.insert(Tech::Militia, TechStatus::Active);

        state.update_corruption();

        // Since both have the same cost and exceed capacity, both should become Corrupted.
        // This ensures the sort didn't panic.
        assert_eq!(state.status(Tech::MetalWorking), TechStatus::Corrupted);
        assert_eq!(state.status(Tech::Militia), TechStatus::Corrupted);
    }

    #[test]
    fn test_placement_succeeds_if_tech_unlocked() {
        let mut world = World::new();
        let mut state = TechState {
            total_capacity: 100.0,
            ..Default::default()
        };
        state.unlock(Tech::MetalWorking);
        world.insert_resource(state);
        world.insert_resource(MessageLog::default());

        world.insert_resource(ColonyResources {
            wood: 100.0,
            stone: 100.0,
            ore: 10.0,
            ..Default::default()
        }); // Resources + Cost checks

        // Setup Grid
        world.insert_resource(TerrainGrid {
            width: 10,
            height: 10,
            tiles: vec![TerrainType::Grass; 100],
        });
        world.insert_resource(crate::layer1::building::OccupiedTiles::default());

        // Try to place Smelter
        let success = try_place_building(&mut world, 5, 5, BuildingType::Smelter);

        assert!(success);
    }

    use crate::layer1::memetics::MemeticCarrier;

    #[test]
    fn test_unlocking_hazardous_tech_infects_researcher() {
        use crate::layer1::actions::{AssignedTo, AssignmentType};
        use crate::layer1::map::GridPosition;
        use crate::layer1::pop::Pop;

        let mut world = World::new();
        // Setup TechState, Resources, and a Researcher Pop
        let tech_state = TechState {
            total_capacity: 1000.0,
            ..Default::default()
        };
        world.insert_resource(tech_state);
        world.insert_resource(ColonyResources {
            knowledge: 1000.0, // Plenty of knowledge
            ..Default::default()
        });
        world.insert_resource(crate::shared::log::MessageLog::default());

        let researcher = world
            .spawn((
                Pop,
                AssignedTo {
                    assignment_type: AssignmentType::LibraryWorker,
                    entity: Entity::PLACEHOLDER,
                }, // entity placeholder is fine for assignment type check
                GridPosition::default(),
            ))
            .id();

        // Unlock Tech::VoidWhispers
        let result = unlock_tech(&mut world, Tech::VoidWhispers);

        // Assert success
        assert!(result);
        // Assert researcher is infected
        assert!(world.get::<MemeticCarrier>(researcher).is_some());
    }

    #[test]
    fn test_try_unlock_already_unlocked() {
        let mut state = TechState {
            total_capacity: 100.0,
            used_capacity: 0.0,
            ..Default::default()
        };

        // Initially unlock it
        let first_try = state.try_unlock(Tech::Masonry);
        assert!(first_try);
        assert_eq!(state.used_capacity, Tech::Masonry.storage_cost());

        // Try unlocking again, should return true immediately without adding to used capacity
        let second_try = state.try_unlock(Tech::Masonry);
        assert!(second_try);
        assert_eq!(state.used_capacity, Tech::Masonry.storage_cost()); // Should not double-charge
    }

    #[test]
    fn test_is_researched_vs_is_active() {
        let mut state = TechState {
            total_capacity: 100.0,
            ..Default::default()
        };

        // Neither researched nor active
        assert!(!state.is_researched(Tech::Masonry));
        assert!(!state.is_active(Tech::Masonry));

        // Unlocked -> Both
        state.force_unlock(Tech::Masonry, TechStatus::Active);
        assert!(state.is_researched(Tech::Masonry));
        assert!(state.is_active(Tech::Masonry));

        // Corrupted -> Researched but NOT active
        // To prevent update_corruption from restoring it, we need to drop capacity
        state.total_capacity = 0.0;
        state.update_corruption();
        assert!(state.is_researched(Tech::Masonry));
        assert!(!state.is_active(Tech::Masonry));
        assert_eq!(state.status(Tech::Masonry), TechStatus::Corrupted);
    }
}
pub mod ghost_code;
#[cfg(test)]
mod ghost_code_integration_tests;
#[cfg(test)]
mod ghost_code_tests;

/// Hypno-Learning system (Spec 255).
pub mod hypno_learning;
#[cfg(test)]
mod hypno_learning_tests;

pub mod infinite_archive;
#[cfg(test)]
mod infinite_archive_tests;
pub mod neural_leech;

#[cfg(test)]
mod neural_leech_tests;

pub mod legacy_code;
#[cfg(test)]
mod legacy_code_tests;

/// The Industrial Rhythm system (Spec 260).
pub mod rhythm;
#[cfg(test)]
mod rhythm_tests;

pub mod harmonic;
#[cfg(test)]
mod harmonic_mining_tests;

pub mod cognitive_overclocking;
pub mod event_horizon_tap;
pub use cognitive_overclocking::*;
pub mod machine_awakening;
pub use machine_awakening::*;
pub mod martyrs_engine;

pub mod rogue_automation_cults;

pub mod living_archive;
pub mod symbiotic_data_weavers;
pub mod symbiotic_habitation;
pub mod teleporter;
pub mod temporal_smuggling;
pub use symbiotic_data_weavers::*;
pub mod black_market_genemods;
pub mod nostalgia_engine;
pub use nostalgia_engine::*;

/// Kinetic harpoon tether launchers (Spec 324).
///
/// The module stays private and re-exports explicitly: `physics::harpoon`
/// already owns the `harpoon` module name at the `layer1` level, so a glob
/// re-export here would trip `ambiguous_glob_reexports`.
mod harpoon;
pub use harpoon::{
    active_winch_count, handle_harpoon_impact_system, harpoon_launch_system, harpoon_status_label,
    harpoon_winch_system, launcher_count, orbiting_wanderer_count, spawn_passing_wanderer_system,
    BodyStatus, HarpoonImpactEvent, HarpoonLaunchEvent, HarpoonLauncher, WandererBody, WandererDirector,
    WandererKind, WinchSystem, harpoon_public_strings, CATCH_DAMAGE, CATCH_RADIUS, SNAP_DAMAGE, SNAP_DEBRIS_FEED,
    SNAP_RADIUS, WINCH_DEFAULT_STRENGTH, WINCH_POWER_DRAW, WINCH_PROGRESS_PER_TICK,
};
